### ISSUE TITLE
Initial release preparation meta

### ISSUE THREAD

**Issue by tfeb** [MetOffice/cmip6-dreq-interface#5]
Things that need to be done
- [x] Clean up branches at MO: `dqi-development` needs to go or be recreated at least.
- [x] Release notes
- [x] Merge to `master` and push `master` to GH and hence home.
- [x] Decide on a release tagging scheme: it it's not YYYMMDD then this needs to be justified.
- [x] Tag it.
- [x] Push.

Some of these mean that the release can't happen until I can fix things on the MO repo: so it will need to be Monday, not Friday.
